{{- if and .Values.postgres.enabled .Values.postgres.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.postgres.sealedSecret.name }}
  namespace: {{ .Values.namespaces.vehicle }}
spec:
  encryptedData:
    POSTGRES_USER: {{ .Values.postgres.sealedSecret.encryptedData.POSTGRES_USER | quote }}
    POSTGRES_PASSWORD: {{ .Values.postgres.sealedSecret.encryptedData.POSTGRES_PASSWORD | quote }}
    POSTGRES_DB: {{ .Values.postgres.sealedSecret.encryptedData.POSTGRES_DB | quote }}
  template:
    metadata:
      name: {{ .Values.postgres.sealedSecret.name }}
      namespace: {{ .Values.namespaces.vehicle }}
{{- end }}