{{- if .Values.vehicleCore.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vehicleCore.configMapName }}
  namespace: {{ .Values.namespaces.vehicle }}
data:
  POSTGRES_HOST: {{ .Values.vehicleCore.config.postgresHost }}
  POSTGRES_PORT: {{ .Values.vehicleCore.config.postgresPort }}
{{- end }}